### PR TITLE
Add allow-root to kibana startup

### PR DESCRIPTION
**Pull request by nojan1**
Was not able to make it work otherwise...

### CODE REVIEW

**Comment by nshou** [comment]
Interesting. Did you see the same issue (cannot run as root) for Elasticsearch as well? Just googling found that you also need to add an option "-Des.insecure.allow.root=true" to Elasticsearch too in order to run it as root. If it is the case, I'd also like you to add the option to the Elasticsearch side arguments and merge two changes at a time. Thanks!

**Comment by nojan1** [comment]
I only got a warning from kibana however it it possible that elasticsearch failed as well. Just that it was more quiet about it... I will add the option to elasticsearch.

**Comment by nojan1** [comment]
Actually I just tried it again and it works fine without the extra argument to elasticsearch. The dockerfile also specifies that the user should be "elasticsearch" so I have no idea why kibana felt the need to start as root... Anyhow since it works as it does, do you still want me to add the parameter to elasticsearch?

**Comment by nshou** [comment]
Thank you so much for your help, nojan1!

**Pull request merged**
