### PR TITLE
dev: small cleanup/rewrite merge

### PR DESCRIPTION
**Pull request by txj-xyz**
~~I have one more patch I want to add to the scope of this project to enable Random password generation.~~ 
Completed in 91fd0ad2279eb4f6f497f629dc30b3f8eee31594

- fix: remove random unused `ELASTIC_RANDOM_PASSWORD` variable.
- feat: predefined password & randomized password on boot

Implemented via: https://discuss.elastic.co/t/automate-elasticsearch-reset-password-in-bash-script/317429/6

### CODE REVIEW

**Comment by txj-xyz** [comment]
Updated docs as well.

**Comment by txj-xyz** [comment]
Honestly, at this point I have once again re-coded things once more, I'd hoenstly consider this `v3` at this point lol.

Here is a test image bootup after the recode.

The README.md has been cleaned up as well rewritten quickly

https://github.com/nshou/elasticsearch-kibana/blob/308a6d01f6ff622ed04acecd1ed70d7be14d312d/README.md

**Comment by txj-xyz** [comment]
@nshou

**Comment by txj-xyz** [comment]
@nshou Going to close this and maintain my own fork, feel free to ping me if you want an update

**Comment by nshou** [comment]
Many points intrigue me. Could you please reopen it, if you don't mind @txj-xyz?

**Pull request closed without merging**
